export const projects = [
  {
    id: 1,
    title: "Dental Care UI",
    studio: "Branding",
    team: true,
    like: 136,
    view: "20k",
    image: "/assets/img1.webp",
    icon: "/assets/icon1.webp",
  },
  {
    id: 2,
    title: "Dental Care UI",
    studio: "Emote",
    team: true,
    like: 246,
    view: "23.7k",
    image: "/assets/img2.webp",
    icon: "/assets/icon2.webp",
  },
  {
    id: 3,
    title: "Dental Care UI",
    studio: "SlabPixel",
    team: true,
    like: 149,
    view: "2.5k",
    image: "/assets/img3.webp",
    icon: "/assets/icon3.webp",
  },
  {
    id: 4,
    title: "Dental Care UI",
    studio: "Phenomenon",
    team: true,
    like: 188,
    view: "22.4k",
    image: "/assets/img4.webp",
    icon: "/assets/icon4.webp",
  },
  {
    id: 5,
    title: "Dental Care UI",
    studio: "FANCY",
    team: true,
    like: 288,
    view: "14.7k",
    image: "/assets/img5.webp",
    icon: "/assets/icon5.webp",
  },
  {
    id: 6,
    title: "Dental Care UI",
    studio: "RobDavis",
    team: true,
    like: 141,
    view: "5.5k",
    image: "/assets/img6.webp",
    icon: "/assets/icon6.webp",
  },
  {
    id: 7,
    title: "Dental Care UI",
    studio: "We grow",
    team: true,
    like: 66,
    view: "7.6k",
    image: "/assets/img7.webp",
    icon: "/assets/icon7.webp",
  },
  {
    id: 8,
    title: "Dental Care UI",
    studio: "tubik arts",
    team: true,
    like: 30,
    view: "2.1k",
    image: "/assets/img8.webp",
    icon: "/assets/icon8.webp",
  },
  {
    id: 9,
    title: "Dental Care UI",
    studio: "Peppermint",
    team: true,
    like: 46,
    view: "2.4k",
    image: "/assets/img9.webp",
    icon: "/assets/icon9.webp",
  },
  {
    id: 10,
    title: "Dental Care UI",
    studio: "WixStudio",
    team: true,
    like: 82,
    view: "7.8k",
    image: "/assets/img10.webp",
    icon: "/assets/icon10.webp",
  },
  {
    id: 11,
    title: "Dental Care UI",
    studio: "Inhouse",
    team: true,
    like: 47,
    view: "784",
    image: "/assets/img11.webp",
    icon: "/assets/icon11.webp",
  },
  {
    id: 12,
    title: "Dental Care UI",
    studio: "Vektora",
    team: true,
    like: 63,
    view: "5.8k",
    image: "/assets/img12.webp",
    icon: "/assets/icon12.webp",
  },
  {
    id: 13,
    title: "Dental Care UI",
    studio: "James",
    team: true,
    like: 22,
    view: "1.5k",
    image: "/assets/img13.webp",
    icon: "/assets/icon13.webp",
  },
  {
    id: 14,
    title: "Dental Care UI",
    studio: "ZeyoxStudio",
    team: true,
    like: 142,
    view: "12k",
    image: "/assets/img14.webp",
    icon: "/assets/icon14.webp",
  },
  {
    id: 15,
    title: "Dental Care UI",
    studio: "Gregory",
    team: true,
    like: 56,
    view: "2.7k",
    image: "/assets/img15.webp",
    icon: "/assets/icon15.webp",
  },
];

export const footerMenu1 = [
  "For designers",
  "Hire talent",
  "Inspiration",
  "Advertising",
  "Blog",
  "About",
  "Careers",
  "Support",
];

export const footerMenu2 = ["© 2025 Dribbble", "Terms", "Privacy", "Cookies"];

export const footerMenu3 = [
  "Jobs",
  "Designers",
  "Freelancers",
  "Tags",
  "Places",
  "Resources",
];

export const categories = ["Discover", "Animation", "Branding", "Mobile"];

export const socialIcons = [
  {
    src: "/assets/twitterlogo.jpeg",
    alt: "Twitter",
    width: "w-7",
    height: "h-6",
  },
  {
    src: "/assets/facebooklogo.jpeg",
    alt: "Facebook",
    width: "w-6",
    height: "h-6",
  },
  {
    src: "/assets/instagramlogo.jpeg",
    alt: "Instagram",
    width: "w-8",
    height: "h-6",
  },
  {
    src: "/assets/pinterestlogo.jpeg",
    alt: "Pinterest",
    width: "w-6",
    height: "h-5",
  },
];

export const squareIconButtons = [
  { content: "Explore", src: "/assets/arrow-down.png" },
  { content: "Hire a Designer", src: "/assets/arrow-down.png" },
];

export const squareButtons = [{ content: "Find Jobs" }, { content: "Blog" }];
